#!/bin/sh

workspace="$1"
shift

if [ "$TERM_PROGRAM" = vscode ] && [ -n "$VSCODE_IPC_HOOK_CLI" ]; then
    if [ "$WORKSPACE_PICKING" = "1" ] || [ "$WORKSPACE_NEW" = "1" ]; then
        unset WORKSPACE_PICKING WORKSPACE_NEW
        tmx -d "$workspace" "$@"
        exec code .
    else
        exec tmx "$workspace" "$@"
    fi
else
    exec tmx "$workspace" "$@"
fi
