#!/bin/sh
# shellcheck disable=SC2016

# shellcheck source=./common-workspace
. "$(dirname "$0")/common-workspace"

die() {
    fmt="${1:-ERROR}"
    shift
    # shellcheck disable=SC2059
    printf >&2 "$fmt" "$@"
    exit 1
}

usage() {
    echo >&2 "${0##*/} [options] WORKSPACE_NAME_OR_PATH"
    echo >&2
    echo >&2 "Options:"
    echo >&2
    echo >&2 "  -n  Force a new session, kill any existing sessions for this workspace"
    echo >&2 "  -k  Only kill any existing sessions for this workspace"
    exit 2
}

new=0
kill=0
while getopts knh opt; do
    case "$opt" in
        k)
            kill=1
            ;;
        n)
            new=1
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    usage
fi

workspace="$1"
shift

if [ -z "$WORKSPACE_PROJECT_ROOT" ]; then
    WORKSPACE_PROJECT_ROOT="$PWD"
fi

case "$workspace" in
    /*)
        case "$workspace" in
            "$WORKSPACE_PROJECT_ROOT/"*)
                name="${workspace#$WORKSPACE_PROJECT_ROOT/}"
                ;;
            *)
                name="${workspace##*/}"
                ;;
        esac
        ;;
    *)
        name="$workspace"
        listed="$(list-workspaces | grep "/$workspace$" | head -n 1)"
        if [ -n "$listed" ]; then
            workspace="$WORKSPACE_PROJECT_ROOT/$listed"
        else
            workspace="$WORKSPACE_PROJECT_ROOT/$workspace"
        fi
        ;;
esac

if ! [ -d "$workspace" ]; then
    die 'Specified workspace `%s` does not exist' "$workspace"
fi
if ! [ -e "$workspace/.workspace" ]; then
    die 'Specified workspace `%s` is not recognized' "$workspace"
fi

if [ -e "$workspace/.workspace-setup" ]; then
    set -- "$workspace/.workspace-setup"
fi

if [ $new -eq 1 ] || [ $kill -eq 1 ]; then
    if [ -n "$WORKSPACE_KILL_SESSION" ]; then
        command $WORKSPACE_KILL_SESSION "$name"
    fi
fi

cd "$workspace" || exit 1

if [ $kill -eq 0 ]; then
    command $WORKSPACE_ATTACH "$name" "$SHELL" vimsession "$@"
fi
