#!/bin/sh
# shellcheck disable=SC2016,SC2086

# shellcheck source=./common-workspace
. "$(dirname "$0")/common-workspace"

die() {
    fmt="${1:-ERROR}"
    shift
    # shellcheck disable=SC2059
    printf >&2 "$fmt" "$@"
    exit 1
}

usage() {
    echo >&2 "${0##*/} [options] WORKSPACE_NAME_OR_PATH"
    echo >&2
    echo >&2 "Options:"
    echo >&2
    echo >&2 "  -n  Force a new session, kill any existing sessions for this workspace"
    echo >&2 "  -k  Only kill any existing sessions for this workspace"
    echo >&2
    echo >&2 "Available workspaces:"
    echo >&2
    list-workspaces | sed -e 's#^#  #' >&2
    exit 2
}

new=0
kill=0
picking=0
while getopts knph opt; do
    case "$opt" in
        k)
            kill=1
            ;;
        n)
            new=1
            ;;
        p)
            picking=1
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    if ! [ -e .workspace ]; then
        usage
    fi
    workspace="$PWD"
    if [ -z "$WORKSPACE_PROJECT_ROOT" ]; then
        WORKSPACE_PROJECT_ROOT="${PWD%/*}"
    fi
else
    workspace="$1"
    shift

    if [ -z "$WORKSPACE_PROJECT_ROOT" ]; then
        WORKSPACE_PROJECT_ROOT="$PWD"
    fi
fi

case "$workspace" in
    /*)
        case "$workspace" in
            "$WORKSPACE_PROJECT_ROOT/"*)
                name="${workspace#$WORKSPACE_PROJECT_ROOT/}"
                ;;
            *)
                name="${workspace##*/}"
                ;;
        esac
        ;;
    *)
        name="$workspace"
        listed="$(list-workspaces | grep "/$workspace$" | head -n 1)"
        if [ -n "$listed" ]; then
            workspace="$WORKSPACE_PROJECT_ROOT/$listed"
        else
            workspace="$WORKSPACE_PROJECT_ROOT/$workspace"
        fi
        ;;
esac

if ! [ -d "$workspace" ]; then
    die 'Specified workspace `%s` does not exist' "$workspace"
fi
if ! [ -e "$workspace/.workspace" ]; then
    die 'Specified workspace `%s` is not recognized' "$workspace"
fi

if [ -e "$workspace/.workspace-setup" ]; then
    set -- "$workspace/.workspace-setup"
fi

if [ $new -eq 1 ] || [ $kill -eq 1 ]; then
    if [ -n "$WORKSPACE_KILL_SESSION" ]; then
        command $WORKSPACE_KILL_SESSION "$name"
    fi
fi

cd "$workspace" || exit 1

if [ $kill -eq 0 ]; then
    VISUAL="${VISUAL:-${EDITOR:-vim}}"
    if [ "$VISUAL" = "vim" ] || [ "$VISUAL" = "nvim" ]; then
        set -- 'vimsession .description' "$@"
    fi
    touch .workspace
    command env WORKSPACE_PICKING="$picking" WORKSPACE_NEW="$new" $WORKSPACE_ATTACH "$name" "$SHELL" "$@"
fi
