#!/bin/sh
# shellcheck disable=SC2031

# shellcheck source=./common-workspace
. "$(dirname "$0")/common-workspace"

usage() {
    echo >&2 "${0##*/} [options] WORKSPACE_NAME"
    echo >&2
    echo >&2 "Options:"
    echo >&2 "  -f  Force. Removes any existing workspace of this name."
    if [ -n "$WORKSPACE_SETUP_SCRIPT" ] && [ -e "$WORKSPACE_SETUP_SCRIPT" ]; then
        echo >&2
        (cd "$tmpdir" && sh "$WORKSPACE_SETUP_SCRIPT" -h) 2>&1 | sed -e 's/^/  /' >&2
    fi
    exit 2
}

die() {
    fmt="${1:-ERROR}"
    shift
    # shellcheck disable=SC2059
    printf >&2 "$fmt" "$@"
    exit 1
}

quoted_args() {
    python3 -c 'import sys,shlex; print(" ".join(shlex.quote(a) for a in sys.argv[1:]))' "$@"
}

force=0
while getopts fh opt; do
    case "$opt" in
        f)
            force=1
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    usage
fi

name="$1"
shift

if [ "$1" = "--" ]; then
    shift
fi

scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
project_root="$PWD"
attach-workspace -k "$project_root/$name"
if [ -e "$name" ] || [ -h "$name" ]; then
    if [ $force -eq 1 ]; then
        rm -rf "$name"
    else
        die "Workspace %s already exists" "$name"
    fi
fi

mkdir -p "$name" || die
echo "$name" >"$name/.workspace"
cd "$name" || die

if [ -n "$WORKSPACE_SETUP_SCRIPT" ]; then
    if [ ! -e "$WORKSPACE_SETUP_SCRIPT" ]; then
        if [ -e "$project_root/$WORKSPACE_SETUP_SCRIPT" ]; then
            WORKSPACE_SETUP_SCRIPT="$project_root/$WORKSPACE_SETUP_SCRIPT"
        elif [ -e "$WORKSPACE_PROJECT_ROOT/$WORKSPACE_SETUP_SCRIPT" ]; then
            WORKSPACE_SETUP_SCRIPT="$WORKSPACE_PROJECT_ROOT/$WORKSPACE_SETUP_SCRIPT"
        else
            WORKSPACE_SETUP_SCRIPT="$scriptdir/setup-workspace-default"
        fi
    fi
    if [ -e "$WORKSPACE_SETUP_SCRIPT" ]; then
        echo '#!/bin/sh' >.workspace-setup
        echo "topdir='$project_root'" >>.workspace-setup
        printf 'set -- %s\n' "$(quoted_args "$@")" >>.workspace-setup
        printf '. "%s" "$@" && rm -f "$0"\n' "$WORKSPACE_SETUP_SCRIPT" >>.workspace-setup
        chmod +x ./.workspace-setup
    fi
fi

attach-workspace -n "$project_root/$name"
