#!/bin/sh

usage() {
    echo >&2 "${0##*/} [options] [FZF_QUERY..]"
    echo >&2
    echo >&2 "Options:"
    echo >&2 "  -d DECORATE_ARGS  Pass DECORATE_ARGS to decorate-workspace"
    exit 2
}

decorate_args=
while getopts d:h opt; do
    case "$opt" in
        d)
            decorate_args="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

case "$OSTYPE" in
    darwin*)
        alias sed=gsed
        ;;
esac

pick_workspace () {
    list-workspaces -s -c always \
        | if [ "$decorate" -eq 1 ]; then
              sed -r "s/\x1B\[(([0-9]+)(;[0-9]+)*)?[m,K,H,f,J]//g" \
                  | eval "\$WORKSPACE_DECORATE" "$decorate_args"
          else
              cat
          fi \
        | fzf-tmux --ansi --no-hscroll --tiebreak=index --no-sort -0 -q "$*" \
        | if [ "$decorate" -eq 1 ]; then
              "$WORKSPACE_UNDECORATE"
          else
              sed -r "s/\x1B\[(([0-9]+)(;[0-9]+)*)?[m,K,H,f,J]//g"
          fi
}

if [ -e "$WORKSPACE_DECORATE" ] && [ -e "$WORKSPACE_UNDECORATE" ]; then
    decorate=1
else
    decorate=0
fi

workspace="$(pick_workspace "$@")"
if [ -n "$workspace" ]; then
    exec attach-workspace -p "$workspace"
fi
