#!/bin/sh

pick_workspace () {
    list-workspaces -s -c always \
        | fzf-tmux --ansi --no-hscroll --tiebreak=index --no-sort -0 \
        | sed -r "s/\x1B\[(([0-9]+)(;[0-9]+)*)?[m,K,H,f,J]//g"
}

workspace="$(pick_workspace)"
if [ -n "$workspace" ]; then
    exec attach-workspace "$workspace"
fi
